server:
  port: 8084
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: lb://service-consumer
#                uri: http://hao123.com
        predicates:
        - Path=/index
alibaba:
  cloud:
    access-key: ***
    secret-key: ***
  edas:
    namespace: cn-hangzhou

